name: Docker CI/CD
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: '${{ secrets.DOCKER_USERNAME }}/streamlit-ner-app:latest'
      - name: Run Docker container
        run: >
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME
          }}/streamlit-ner-app:latest
      - name: Verify app is running
        run: |
          sleep 30 # wait for the container to fully start
          curl -f http://localhost:8080 || exit 1
